// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihrvpqrdllyiwolchxfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlocnZwcXJkbGx5aXdvbGNoeGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTQ1MzAsImV4cCI6MjA1OTA3MDUzMH0.HBHFadO218Cy4UH3tHy1f9gbM4SWOlQwvlw4P7ihUEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);